//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemiClean.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductDocument
    {
        public byte[] DocumentContent { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public int ProductId { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
